---
title: "UKAlc_Merging_Descriptives"
author: "Anna Patterson"
date: "2023-09-28"
output: html_document
---

```{r}
library(tidyverse)

#Anisha's Paths
am_qual <- read.csv("C:/Users/anish/Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/AM_Qualtrics_csv.csv")

pm_qual <- read.csv("C:/Users/anish/Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/PM_Qualtrics_csv.csv") 

am_rc <- read.csv("C:/Users/anish/Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/AM_REDCap_csv.csv")

pm_rc <- read.csv("C:/Users/anish/Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/PM_REDCap_csv.csv")


#Anna's Paths

am_qual <- read.csv("/Users/apatte21/Library/CloudStorage/Box-Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/AM_Qualtrics_csv.csv")


pm_qual <- read.csv("/Users/apatte21/Library/CloudStorage/Box-Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/PM_Qualtrics_csv.csv")

am_rc <- read.csv("/Users/apatte21/Library/CloudStorage/Box-Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/AM_REDCap_csv.csv")

pm_rc <- read.csv("/Users/apatte21/Library/CloudStorage/Box-Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/UKALC/02_datasets/UKALC_DAILY/02_data_prep_workspace/PM_REDCap_csv.csv")
```

ID's in am_qual: 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 126

ID's in a_rc: [1] "123"       "124"       "125"       "125b"      "125c"      "125d"      "127"       "127 (new)" "128"      
[10] "129"       "130"       "131"       "132"       "133"       "134"       "134b"      "135"       "136"      
[19] "138"       "139"       "139b"      "140"       "141"       "142"       "142b"      "143"       "144"      
[28] "145"       "146"       "147"       "148"       "149"       "150"       "152"       "153"       "154"      
[37] "155"       "156"       "157"       "158"       "159"       "160"       "161"       "162"       "163"      
[46] "164"       "165"       "166"       "166a"      "166b"      "167"       "168"       "169"       "170"      
[55] "171"       "172"       "173"       "174"       "175"       "176"       "177"       "178"       "179"      
[64] "180"       "181"       "182"       "183"       "184"       "185"   

ID's in pm_qual: 101 102 103 104 105 106 107 108 109 111 112 113 114 115 116 117 118 119 120 121 122 126 

ID's in pm_rc: [1] "123"       "124"       "125"       "125b"      "125c"      "125d"      "127"       "127 (new)" "128"      
[10] "129"       "130"       "131"       "132"       "133"       "134"       "134b"      "135"       "136"      
[19] "138"       "139"       "139b"      "140"       "141"       "142"       "142b"      "143"       "144"      
[28] "145"       "146"       "147"       "148"       "149"       "150"       "152"       "153"       "154"      
[37] "155"       "156"       "157"       "158"       "159"       "160"       "161"       "162"       "163"      
[46] "164"       "165"       "166"       "166a"      "166b"      "167"       "168"       "169"       "170"      
[55] "171"       "172"       "173"       "174"       "175"       "176"       "177"       "178"       "179"      
[64] "180"       "181"       "182"       "183"       "184"       "185"    



#IDs in am qualtrics are numerical, IDs in rc are string form -- we are unsure if letters at end of IDs are distinct IDs or not 
```{r}
am_data <- merge(am_qual, am_rc, by = c("ID", "DateTime"), all = T)

pm_data <- merge(pm_qual, pm_rc, by = c("ID", "DateTime"), all = T)

```

```{r}
intersect(am_data$ID, pm_data$ID)

setdiff(am_data$ID, pm_data$ID)

am_pm_part <- intersect(am_data$ID, pm_data$ID)
length(am_pm_part)

gsub("[^0-9.-]", "", pm_data$ID)
gsub("[^0-9.-]", "", am_data$ID)

am_part.u <- gsub("[^0-9.-]", "", am_data$ID)
pm_part.u <- gsub("[^0-9.-]", "", pm_data$ID)

unique(am_part.u)
unique(pm_part.u)

am_part.u.n <- unique(am_part.u)
pm_part.u.n <- unique(pm_part.u)

length(am_part.u.n)
length(pm_part.u.n)
```

#After correcting for duplicates, we have n = 83 for am data and n = 82 for pm data 
```{r}
strsplit(am_data, )
```


#IDs in both am and pm datasets: 
[1] "101"       "102"       "103"       "104"       "105"       "106"       "107"       "108"       "109"      
[10] "111"       "112"       "113"       "114"       "115"       "116"       "117"       "118"       "119"      
[19] "120"       "121"       "122"       "123"       "124"       "125"       "125b"      "125c"      "125d"     
[28] "126"       "127"       "127 (new)" "128"       "129"       "130"       "131"       "132"       "133"      
[37] "134"       "134b"      "135"       "136"       "138"       "139"       "139b"      "140"       "141"      
[46] "142"       "142b"      "143"       "144"       "145"       "146"       "147"       "148"       "149"      
[55] "150"       "152"       "153"       "154"       "155"       "156"       "157"       "158"       "159"      
[64] "160"       "161"       "162"       "163"       "164"       "165"       "166"       "166a"      "166b"     
[73] "167"       "168"       "169"       "170"       "171"       "172"       "173"       "174"       "175"      
[82] "176"       "177"       "178"       "179"       "180"       "181"       "182"       "183"       "184"      
[91] "185"  

#IDs not in both am and pm datasets: [1] "110" 
